name: export-x-solution
# Export solution from DEV environment
# unpack it and prepare, commit and push a git branch with the changes

on:
  workflow_dispatch:
    inputs:
      # Enter this value (required)
      solution_name:
        description: 'name of the solution to worked on from Power Platform'
        required: true

env:
#edit your values here
  DEV_ENVIRONMENT_URL: https://orgd1223c66.crm8.dynamics.com         
  TEST_ENVIRONMENT_URL: https://org0d925923.crm8.dynamics.com/
  USERNAME: anjaliPatel@vedlogicsolutionpvtltd.onmicrosoft.com
  APPLICATION_ID: 6cae9a3a-c9a1-47f4-b2d3-aecdae001bf8
  TENANT_ID: 414d6624-89b5-405d-9a0d-414b798782e0
  CLIENT_SECRET: ${{ secrets.PowerPlatformCICD }}
  SOLUTION_EXPORTED_FOLDER: out/exported/
  SOLUTION_FOLDER: out/solutions/
  SOLUTION_TARGET_FOLDER: solutions/

jobs:
  export-from-dev:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: who-am-i dev
      uses: microsoft/powerplatform-actions/who-am-i@0.4.0
      with:
        environment-url: ${{env.DEV_ENVIRONMENT_URL}}
        app-id: ${{env.APPLICATION_ID}}
        client-secret: ${{ secrets.CLIENT_SECRET }}
        tenant-id: ${{env.TENANT_ID}}

    - name: export-solution action
      uses: microsoft/powerplatform-actions/export-solution@0.4.0
      with:
        environment-url: ${{env.DEV_ENVIRONMENT_URL}}
        app-id: ${{env.APPLICATION_ID}}
        client-secret: ${{ secrets.CLIENT_SECRET }}
        tenant-id: ${{env.TENANT_ID}}
        solution-name: ${{ github.event.inputs.solution_name }}
        solution-output-file: ${{ env.SOLUTION_EXPORTED_FOLDER}}/${{ github.event.inputs.solution_name }}.zip

    - name: unpack-solution action
      uses: microsoft/powerplatform-actions/unpack-solution@0.4.0
      with:
        solution-file: ${{ env.SOLUTION_EXPORTED_FOLDER}}/${{ github.event.inputs.solution_name }}.zip
        solution-folder: ${{ env.SOLUTION_FOLDER}}/${{ github.event.inputs.solution_name }}
        solution-type: 'Unmanaged'
        overwrite-files: true

    - name: branch-solution, prepare it for a PullRequest
      uses: microsoft/powerplatform-actions/branch-solution@0.4.0
      with:
        solution-folder: ${{ env.SOLUTION_FOLDER}}/${{ github.event.inputs.solution_name }}
        solution-target-folder: ${{ env.SOLUTION_TARGET_FOLDER}}/${{ github.event.inputs.solution_name }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        allow-empty-commit: true
