name: import-x-solution
# import solution to test environment as un-managed 

on:
  workflow_dispatch:
    inputs:
      # Enter this value (required)
      solution_name:
        description: 'name of the solution to worked on from Power Platform'
        required: true

env:
#edit your values here
  BUILD_ENVIRONMENT_URL: https://org830f9536.crm8.dynamics.com/
  APPLICATION_ID: 91a80443-4c03-4c28-98ee-3b7c3a30890b
  TENANT_ID: 414d6624-89b5-405d-9a0d-414b798782e0
  CLIENT_SECRET: ${{ secrets.PowerPlatformCICD }}
  SOLUTION_SHIPPING_FOLDER: out/ship/
  SOLUTION_OUTBOUND_FOLDER: out/solutions/
  SOLUTION_SOURCE_FOLDER: solutions/
  SOLUTION_RELEASE_FOLDER: out/release

jobs:
  import-solution:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: Pack solution
      uses: microsoft/powerplatform-actions/pack-solution@0.4.0
      with:
        solution-folder: ${{ env.SOLUTION_SOURCE_FOLDER }}/${{ github.event.inputs.solution_name }}
        solution-file: ${{ env.SOLUTION_OUTBOUND_FOLDER }}/${{ github.event.inputs.solution_name }}.zip
        solution-type: Unmanaged

    - name: Import solution as unmanaged to uat env
      uses: microsoft/powerplatform-actions/import-solution@v0
      with:
        environment-url: ${{env.BUILD_ENVIRONMENT_URL}}
        app-id: ${{env.APPLICATION_ID}}
        client-secret: ${{ secrets.CLIENT_SECRET }}
        tenant-id: ${{env.TENANT_ID}}
        solution-file: ${{ env.SOLUTION_OUTBOUND_FOLDER }}/${{ github.event.inputs.solution_name }}.zip
        force-overwrite: true
        publish-changes: true
