name: Release action
# Call the reusable workflow release-solution-to-prod-with-inputs.yml
# Release your solution to prod when you create a new release.

on:
  release:
      types: [created]        

jobs:
  Release-solution-CICDDemo:
    uses: ./.github/workflows/release-solution-to-prod-with-inputs.yml
    with:
      #You can specify the solution name here
      solution_name: CICDDemo
      #Update your values here
      BUILD_ENVIRONMENT_URL: https://org0d925923.crm8.dynamics.com
      PRODUCTION_ENVIRONMENT_URL: https://org830f9536.crm8.dynamics.com/
      CLIENT_ID: 91a80443-4c03-4c28-98ee-3b7c3a30890b
      TENANT_ID: 414d6624-89b5-405d-9a0d-414b798782e0     
    secrets:
      envSecret: ${{ secrets.PowerPlatformCICD }}
